console.log("---------- Step 1 ---------");
var sweety="Sweety";
var cutie="Cutie";
console.log("---------Before Swap--------");
console.log("sweety:",sweety,"cutie:",cutie);
var temp=sweety;
sweety=cutie;
cutie=temp;
console.log("-------After Swap--------");
console.log("sweety:",sweety,"cutie:",cutie);

console.log("--------- Step 2 ----------");
var num1=100;
var num2=200;
var num3=300;
console.log("---------Before Swap--------");
console.log("Num1:",num1,"Num2:",num2,"Num3:",num3);
var temp=num1;
num1=num2;
num2=num3;
num3=temp;
console.log("---------After Swap--------");
console.log("Num1:",num1,"Num2:",num2,"Num3:",num3);